- Dockerfile
This is based on a comment of @rgauss . It clearly reduces the size of the image somewhat. (See JIRA for details).
> DEPLOY-412 Reduce image size

- Dockerfile
implemented the security recommended by : https://tomcat.apache.org/tomcat-8.0-doc/security-howto.html#Non-Tomcat_settings
> REPO-3154: implement basic security for filesystem and user that runs the tomcat server

- README.md
Some awesome changes to the README.
> DEPLOY-275: Assure Guidelines are clear on use of images wrt immutability

- Dockerfile
Build is Green
https://bamboo.alfresco.com/bamboo/browse/PS-DBTI7-8
Quay lists it as green.
https://quay.io/repository/alfresco/alfresco-base-tomcat/image/2a79c1d265be974b39c4ab53a6c19769ae18670768697a05bbd206eeec43a97e
> DEPLOY-433 : Version pinning all RPMs is necessary for repeatable builds

- Dockerfile
- build.properties
- scripts/bin/build.sh
- scripts/bin/release.sh
- scripts/etc/common.sh
- scripts/etc/images.sh
- scripts/lib/java.sh
- scripts/lib/tomcat.sh
DEPLOY-575 Stupid GPG
DEPLOY-575 Moving files around (see DEPLOY-574 rework)
DEPLOY-612 fix
Green https://quay.io/repository/alfresco/alfresco-base-tomcat?tab=tags
Logs https://bamboo.alfresco.com/bamboo/browse/PS-DBTIR0-JOB1-11/log
> DEPLOY-575 Support multiple Java versions

- scripts/etc/images.sh
Reverts Alfresco/alfresco-docker-base-tomcat#22
> Revert "Bump base image to one from Axel Faust at devcon"

- scripts/etc/images.sh
There was no need to add aditional fixes here. Green scan just by getting the latest base java. 
I will change the target after getting a go for the base java.
> DEPLOY-685: Fix image vulnerabilities

- scripts/etc/images.sh
Updating Base java image.
I will update this pr once I get a green flag on the java image.
> DEPLOY-709: Update base java image

- scripts/etc/images.sh
> [DEPLOY-904] Fix NSS vulnerabilities on current base java image

- scripts/etc/images.sh
-Update to use new base-java images
> [DEPLOY-924] Security Vulnerability in Base Java image

- Dockerfile
-Turn off Logging for VersionLoggingListener
> [DEPLOY-930] Security: Information leak in Base Tomcat image

- .github/dependabot.yml
- .travis.yml
- Dockerfile
- README.md
- java-11/centos-7/Dockerfile
- java-11/centos-8/Dockerfile
- java-8/centos-7/Dockerfile
- java-8/centos-8/Dockerfile
Update vulnerabilities on images for DEVOPS-5
> DEVOPS-5 update vulnerabilities

- java-11/centos-7/Dockerfile
- java-11/centos-8/Dockerfile
- java-8/centos-7/Dockerfile
- java-8/centos-8/Dockerfile
Update base java image to release the vulnerability free tomcat one
> OPSEXP-940 fix vulnerabilities updating java base

- Dockerfile
>  OPSEXP-1045 bring the jdk back into the tomcat image

- README.md
OPSEXP-1294
Preview: https://github.com/Alfresco/alfresco-docker-base-tomcat/blob/OPSEXP-1294-readme-rewrite/README.md
> OPSEXP-1294 Update README for new tag naming convention

- .github/workflows/main.yml
Ref: OPSEXP-1737
Essentially to fix ACS-3565
> new images with updated rockylinux images

- .github/workflows/main.yml
- Dockerfile
> OPSEXP-2136: Set env locales properly for Rocky Linux 8

- .github/workflows/bumpVersions.yml
- .github/workflows/main.yml
- Dockerfile
- get-checksum.sh
- get-tomcat-version.sh
- updatecli.d/01_tomcat_version.tpl
- updatecli.d/02_tomcat_checksum.tpl
* Fix branch name and pr title using wrong tomcat version
* Fix unreliable source for finding the latest tomcat version available for each major
OPSEXP-2388
> OPSEXP-2388 Improve automated updates workflow

- .github/workflows/main.yml
- README.md
> OPSEXP-2512 Remove centos support

- .github/workflows/bumpVersions.yml
- .github/workflows/main.yml
- README.md
Ref: OPSEXP-2149
* always docker push - not on [release] commit
* add a scheduled weekly workflow
* apply expire labels on images built from branch
> OPSEXP-2149 Refactor build workflow

- .github/workflows/main.yml
> OPSEXP-2764 Push an additional tag with timestamp

- README.md
> OPSEXP-2931 Point links to support.hyland.com

- .github/workflows/main.yml
- README.md
> OPSEXP-2949 Add JRE 21

- Dockerfile
> OPSEXP-3323: prevent silent failures when verifying the Tomcat Native library
